name: Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.27.0'  # Adjusted to a stable version

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.9.0'

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          name: test-cluster
          wait: true

      - name: Install Helm Chart
        run: |
          helm install rick-and-morty-api ./helm/rick-and-morty-api

      - name: List Resources
        run: |
          kubectl get all --namespace default

      - name: Wait for Application to Be Ready
        run: |
          sleep 10  # Give Helm some time to create resources
          kubectl wait --namespace default \
            --for=condition=available deployment/rick-and-morty-api --timeout=90s

      - name: Test Application Endpoints
        run: |
          curl --fail http://127.0.0.1:30080/healthcheck
          curl --fail "http://127.0.0.1:30080/fetch_characters?species=Human&status=Alive&origin=Earth"
