name: Deploy and Test Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Setup KinD
        uses: helm/kind-action@v1.5.0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Kubernetes cluster
        run: |
          kind create cluster --name test-cluster
          kubectl cluster-info

      - name: Deploy application using Helm
        run: |
          helm install rick-and-morty-api ./helm/rick-and-morty-api
          kubectl get all

      - name: Wait for application to be ready
        run: |
          kubectl wait --namespace default \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/name=rick-and-morty-api \
            --timeout=90s

      - name: Test application endpoints
        run: |
          kubectl port-forward service/rick-and-morty-api 8080:80 &
          sleep 5
          curl http://127.0.0.1:8080/healthcheck
          curl http://127.0.0.1:8080/fetch_characters?species=Human&status=Alive&origin=Earth
